### ISSUE TITLE
Heizoel24

### ISSUE THREAD

**Issue by surger13** [eckonator/MMM-Pelletpreise#1]
Hallo,
vom gleichen Anbieter gibt es ja heizöl24.de. Lässt sich das Modul in diese Richtung erweitern?

VG Dirk

**Comment by eckonator** [comment]
Sind denn die Preise unterschiedlich oder werden dort andere Preise angezeigt? Wenn es die gleichen Preise sind, wüsste ich nicht warum man in die Richtung erweitern wollen würde?

**Comment by surger13** [comment]
Mir ging es um eine Option für Heizöelpreise, sorry wenn ich mich da etwas unglücklich ausgedrückt hatte. Ich kenne mich da überhaupt nicht aus, ob das machbar ist. Mir ist nur aufgefallen, dass es der gleiche Anbieter ist, nur eine andere Website. Vllt. sind da nur kleine Änderungen notwendig.

**Comment by eckonator** [comment]
Ah verstehe - Öl statt Pellets. Kann ich mir gerne mal ansehen :-)

**Comment by surger13** [comment]
Genau ;), ich denke da würden sich aktuell einige freuen, dass auf dem MM sehen zu können.

**Comment by eckonator** [comment]
Hier bitteschön, viel Spaß damit: https://github.com/eckonator/MMM-Oelpreise

**Comment by surger13** [comment]
Hallo Markus,
das ging ja fix. Vielen Dank. Hab es gleich probiert, läuft. 

Es wird angezeigt "Euro / Li" müsste aber richtigerweise "€/ 100l" sein. Aber wir sind ja auf einem guten Weg zu diesem Preis. :D
Lässt sich die Dicke des Graphen irgendwie anpassen? Der Strich ist recht breit. 

Sonst aber top, vielen Dank nochmal. 

Gruß Dirk

**Comment by eckonator** [comment]
Hallo Dirk, das Label habe ich dir angepasst. Zur Strichstärke müsste ich mich erst schlau machen.
